### ISSUE TITLE
how to get the bearer token?

### ISSUE THREAD

**Issue by BrunoCunha1983** [joaodcp/Carris-API#1]

**Comment by joaodcp** [comment]
The value I haven't disclosed here is the first token/api key you need to provide in order to authorise subsequent requests.

The reason I have kept this value a "secret" is because access to data isn't supposed to be public, but mostly because the token changes frequently and I don't want to provide outdated invalid values.

You can intercept the token from the requests the app makes. Carris is using Firebase Remote Config for token distribution, so it should be pretty easy for you to dynamically fetch it.
Keep in mind that this value can and will change unexpectedly (in case you hardcode it into your app).

If you're unable to do as I described above, you can leave a way for me to contact you personally. I'm more than happy to provide you the current valid token.

**Comment by BrunoCunha1983** [comment]
If you dont mind i prefer tour help becouse y'am a noob on programing...
Thanks for you time
I'am from Portugal


BrunoCunha

A quarta, 30/11/2022, 02:06, João Pereira ***@***.***>
escreveu:

**Comment by joaodcp** [comment]
Então não precisamos de andar com "inglesices". Tenho todo o gosto em ajudar.

Envie-me um método de contacto pessoal para falarmos melhor.

**Comment by BrunoCunha1983** [comment]
Boas 961490618

A sexta, 2/12/2022, 11:56, João Pereira ***@***.***> escreveu:

**Comment by BrunoCunha1983** [comment]
Recebeu o meu número?
962490618

A sexta, 2/12/2022, 17:42, Bruno Miguel Canteiro da Cunha <
***@***.***> escreveu:

**Comment by BrunoCunha1983** [comment]
Não me contactou ainda !!!!!!

A sexta, 18/08/2023, 01:12, João Pereira ***@***.***>
escreveu:

**Comment by joaodcp** [comment]
Boa noite,

Não o contactei porque de momento não tenho disponibilidade para o fazer. No entanto, deixo abaixo duas chaves **atualmente válidas** (mais uma vez reitero o facto de estas serem geridas pela CARRIS, pelo que poderão deixar de estar autorizadas a qualquer momento).

`
59736080a00d1dda0aefe21af199747bf33bbcb34b2f23188bb814d4b80e4570
`

`
258a5022a06e7b3496c76e132b6ce5117dc2c8da1f679e66c933552b49253e58
`

Cumps
